development:
  # Discord ボットの設定
  DiscordBot:
    Token: 'Nzg5NjQ2ODI0MjU1NTIwNzY4.X91F6Q.79IV6rCRpa3einCyAM1LCMifIXs'
    ClientID: '789646824255520768'

  # 使用するプラグインを列挙する。大文字小文字を区別するので注意
  Plugins:

  # 追加で読み込む設定ファイル
  Include:
